function renderInsights() {
  const a=analyzeScores(state.info.scores), n=a.valid.length, timing=a.early+a.late;
  const meter=(label,value,right)=>`<div class="metric-row"><span>${label}</span><div class="meter"><i style="width:${Math.min(100,Math.max(0,value))}%"></i></div><strong>${right}</strong></div>`;
  document.getElementById('insights').innerHTML=`
    <article class="card"><p class="eyebrow">DIFFICULTY PROFILE</p><h3>难度表现</h3>${a.groups.map(g=>meter(HARD_NAMES[g.hard].toUpperCase(),g.acc*100,g.count?fmtAggPct(g.acc):'暂无记录')).join('')}<p class="analysis-note">${a.groups.map(g=>`${HARD_NAMES[g.hard].toUpperCase()} ${g.count} 谱面 / ${g.fc} 零 Miss`).join(' · ')}<br>各难度按当前 ACC 聚合设置计算，条形从 0% 起。</p></article>
    <article class="card"><p class="eyebrow">ACCURACY DISTRIBUTION</p><h3>ACC 分布 <span class="tag">${n} 个有判定的谱面</span></h3>${a.bands.map(b=>meter(b.label,n?b.count/n*100:0,b.count+' 谱面')).join('')}<p class="analysis-note">All Perfect：${a.ap} 个谱面。区间包含下界，不包含上界；最高区间包含 100%。</p></article>
    <article class="card"><p class="eyebrow">TIMING BALANCE</p><h3>早晚判定偏向</h3><div class="timing-value">${timing?(a.early===a.late?'早晚均衡':a.early>a.late?'偏早':'偏晚'):'暂无早晚偏差'}</div><div class="timing-bar"><i style="width:${timing?a.early/timing*100:50}%"></i><i style="width:${timing?a.late/timing*100:50}%"></i></div><div class="timing-labels"><span>EARLY · ${a.early}</span><span>LATE · ${a.late}</span></div><p class="analysis-note">统计 Good + Bad 的早晚次数，不含 Perfect / Miss。${timing?'偏早占 '+fmtPct(a.early/timing)+'，偏晚占 '+fmtPct(a.late/timing)+'。':'当前记录没有 Good 或 Bad 判定。'}<br>仅反映这份最佳成绩记录，不能直接推断设备延迟。</p></article>
    <article class="card"><p class="eyebrow">PRACTICE FOCUS</p><h3>优先练习</h3>${a.candidates.length?a.candidates.map((x,i)=>`<div class="practice-item"><span class="practice-rank">0${i+1}</span><div><b>${esc(titleOf(x.score))} · ${HARD_NAMES[x.score.hard]||'?'}</b><small>${fmtPct(accOf(x.score))} · Miss ${x.score.miss} · 可恢复 ${ (x.loss*100).toFixed(2)} 个百分点</small></div></div>`).join(''):'<p class="analysis-note">'+(n?'当前判定没有可恢复的加权损失。':'导入有效成绩后显示练习建议。')+'</p>'}<p class="analysis-note">按 Good / Bad / Miss 转为 Perfect 可恢复的单谱面 ACC 排序，使用当前权重；这是理论空间，不是提分预测。</p></article>`;
}
